---
- name: Configure Layer 3 interfaces
  hosts: switches
  gather_facts: no
  tasks: 
    - name: Import YAML data for switches
      ansible.builtin.set_fact:
        interface_data: "{{ lookup('file', 'interface_data.yaml') | from_yaml }}"
    - name: Configure physical interfaces as Layer 3 interfaces
      cisco.nxos.nxos_config:
        lines: no switchport
        parents: "interface {{ item.interface }}"
      when: item.interface is search("Ethernet")
      #Loop across the devices in YAML file which are keys in Dictionary of YAML file.
      with_items: "{{ interface_data ['%s' | format(inventory_hostname)] }}"
    - name: Configure Layer 3 intefaces on switches
      cisco.nxos.nxos_config:
        lines:
          - "ip address {{ item.ip }}"
          - "description {{ item.description }}"
          - "{{ item.status }}"
        parents: "interface {{ item.interface }}"
      #Loop across the devices in YAML file which are keys in Dictionary of YAML file.
      with_items: "{{ interface_data ['%s' | format(inventory_hostname)] }}"